apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: finops-alerts
  namespace: monitoring
  labels:
    release: prometheus
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
  - name: finops-resource-waste
    rules:
    - alert: HighCPUWaste
      expr: |
        (
          sum(kube_pod_container_resource_requests{resource="cpu",service="prometheus-kube-state-metrics"}) by (namespace) - 
          sum(rate(container_cpu_usage_seconds_total{container!=""}[5m])) by (namespace)
        ) / sum(kube_pod_container_resource_requests{resource="cpu",service="prometheus-kube-state-metrics"}) by (namespace) * 100 > 70
      for: 24h
      labels:
        severity: warning
        category: finops
      annotations:
        summary: "High CPU waste in namespace {{ $labels.namespace }}"
        description: "The CPU resources in namespace {{ $labels.namespace }} are {{ $value | printf \"%.2f\" }}% wasted over the last 24 hours (requested but not used)."

    - alert: HighMemoryWaste
      expr: finops_resource_waste{resource_type="memory"} > 70
      for: 24h
      labels:
        severity: warning
        category: finops
      annotations:
        summary: "High memory waste in namespace {{ $labels.exported_namespace }}"
        description: "The memory waste in namespace {{ $labels.exported_namespace }} is {{ $value | printf \"%.2f\" }}%, which is above the threshold of 70% for the last 24 hours."

  - name: finops-cost-efficiency
    rules:
    - alert: LowCostEfficiencyWarning
      expr: avg(finops_efficiency_score{}) by (exported_namespace) < 50 and avg(finops_efficiency_score{}) by (exported_namespace)  >= 30
      for: 24h
      labels:
        severity: warning
        category: finops
      annotations:
        summary: "Low cost efficiency in namespace {{ $labels.exported_namespace }}"
        description: "The cost efficiency score for namespace {{ $labels.exported_namespace }} is {{ $value | printf \"%.2f\" }}%, which is between 30% and 50% for the last 24 hours."

    - alert: CriticalCostEfficiencyWarning
      expr: avg(finops_efficiency_score{}) by (exported_namespace) < 30
      for: 24h
      labels:
        severity: critical
        category: finops
      annotations:
        summary: "Critical low cost efficiency in namespace {{ $labels.exported_namespace }}"
        description: "The cost efficiency score for namespace {{ $labels.exported_namespace }} is {{ $value | printf \"%.2f\" }}%, which is below the critical threshold of 30% for the last 24 hours."

  - name: finops-cost-anomalies
    rules:
    - alert: CostAnomalyWarning
      expr: avg(finops_anomaly_score{}) by (exported_namespace) > 50 and avg(finops_anomaly_score{}) by (exported_namespace) < 90
      for: 2h
      labels:
        severity: warning
        category: finops
      annotations:
        summary: "Cost anomaly detected in namespace {{ $labels.exported_namespace }}"
        description: "A cost anomaly with score {{ $value | printf \"%.2f\" }}/100 has been detected in namespace {{ $labels.exported_namespace }}. This may indicate unexpected cost increase."
        
    - alert: SevereCostAnomaly
      expr: avg(finops_anomaly_score{}) by (exported_namespace) >= 90
      for: 1h
      labels:
        severity: critical
        category: finops
      annotations:
        summary: "Severe cost anomaly detected in namespace {{ $labels.exported_namespace }}"
        description: "A severe cost anomaly with score {{ $value | printf \"%.2f\" }}/100 has been detected in namespace {{ $labels.exported_namespace }}. Immediate investigation is recommended."
        
  - name: finops-optimization-opportunities
    rules:
    - alert: HighSavingsOpportunity
      expr: sum(finops_optimization_savings{}) by (exported_namespace) > 100
      for: 7d
      labels:
        severity: info
        category: finops
      annotations:
        summary: "High potential savings identified for namespace {{ $labels.exported_namespace }}"
        description: "There is a potential for ${{ $value | printf \"%.2f\" }} monthly savings in namespace {{ $labels.exported_namespace }}. Review the recommendations in the FinOps dashboard."
        
    - alert: OptimizationSavingsAvailable
      expr: count(finops_optimization_savings{} > 0) by (recommendation_type) > 0
      for: 1h
      labels:
        severity: warning
        category: finops
      annotations:
        summary: "Cost optimization opportunities available"
        description: "There are {{ $value }} active '{{ $labels.recommendation_type }}' recommendations that have been pending for over 14 days."

  - name: finops-resource-utilization
    rules:
    - alert: ClusterCPUUnderutilization
      expr: sum(rate(container_cpu_usage_seconds_total{container!=""}[1d])) / sum(kube_node_status_capacity{resource="cpu"}) < 0.3
      for: 7d
      labels:
        severity: warning
        category: finops
      annotations:
        summary: "Cluster underutilized"
        description: "Cluster CPU utilization has been below 30% for 7 days. Consider rightsizing the cluster."

  - name: finops-daily-cost-increase
    rules:
      - alert: DailyCostIncrease
        expr: |
          sum(
            sum(avg_over_time(container_memory_allocation_bytes{job="opencost"}[24h])) by (namespace, instance)
            * on(instance) group_left()
              (node_ram_hourly_cost{job="opencost"} / (1024 * 1024 * 1024))
          +
            sum(avg_over_time(container_cpu_allocation{job="opencost"}[24h])) by (namespace, instance)
            * on(instance) group_left()
              (node_cpu_hourly_cost{job="opencost"})
          ) by (namespace)
          >
          (
            sum(
              sum(avg_over_time(container_memory_allocation_bytes{job="opencost"}[24h] offset 1d)) by (namespace, instance)
              * on(instance) group_left()
                (node_ram_hourly_cost{job="opencost"} offset 1d / (1024 * 1024 * 1024))
            +
              sum(avg_over_time(container_cpu_allocation{job="opencost"}[24h] offset 1d)) by (namespace, instance)
              * on(instance) group_left()
                (node_cpu_hourly_cost{job="opencost"} offset 1d)
            ) by (namespace)
          ) * 1.5
        for: 2h
        labels:
          severity: warning
          category: finops
        annotations:
          summary: "Namespace {{ $labels.namespace }} cost increased by >50%"
          description: "The compute cost for namespace {{ $labels.namespace }} has increased by more than 50% compared to the previous day."

  - name: finops-weekly-cost-increase
    rules:
      - alert: WeeklyCostIncrease
        expr: |
          sum(
            sum(avg_over_time(container_memory_allocation_bytes{job="opencost"}[7d])) by (namespace, instance)
            * on(instance) group_left()
              (node_ram_hourly_cost{job="opencost"} / (1024 * 1024 * 1024))
          +
            sum(avg_over_time(container_cpu_allocation{job="opencost"}[7d])) by (namespace, instance)
            * on(instance) group_left()
              (node_cpu_hourly_cost{job="opencost"})
          ) by (namespace)
          >
          (
            sum(
              sum(avg_over_time(container_memory_allocation_bytes{job="opencost"}[7d] offset 7d)) by (namespace, instance)
              * on(instance) group_left()
                (node_ram_hourly_cost{job="opencost"} offset 7d / (1024 * 1024 * 1024))
            +
              sum(avg_over_time(container_cpu_allocation{job="opencost"}[7d] offset 7d)) by (namespace, instance)
              * on(instance) group_left()
                (node_cpu_hourly_cost{job="opencost"} offset 7d)
            ) by (namespace)
          ) * 1.3
        for: 2h
        labels:
          severity: warning
          category: finops
        annotations:
          summary: "Namespace {{ $labels.namespace }} cost increased by >30%"
          description: "The compute cost for namespace {{ $labels.namespace }} has increased by more than 50% compared to the previous week."
        
  - name: finops-idle-resources
    rules:
    - alert: IdlePersistentVolumes
      expr: kube_persistentvolume_status_phase{phase="Available"} == 1
      for: 7d
      labels:
        severity: warning
        category: finops
      annotations:
        summary: "Idle persistent volume {{ $labels.persistentvolume }}"
        description: "Persistent volume {{ $labels.persistentvolume }} has been available (unused) for 7 days."

    - alert: IdleLoadBalancer
      expr: |
        sum(kube_service_spec_type{type="LoadBalancer"}) by (namespace, service) 
        unless sum(kube_pod_info) by (namespace, service)
      for: 7d
      labels:
        severity: warning
        category: finops
      annotations:
        summary: "Idle LoadBalancer service in namespace {{ $labels.namespace }}"
        description: "LoadBalancer service {{ $labels.service }} in namespace {{ $labels.namespace }} appears to have no backend pods for 7 days."
        