{
 "title": "Node utilization metrics",
 "tags": [
  "cost",
  "utilization",
  "metrics",
  "opencost"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage (Total)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(instance:node_cpu_utilisation:rate5m)*100"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage (Total)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(container_memory_usage_bytes) / SUM(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Usage (GB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (\n  node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"} \n  - \n  node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay\"}\n) /1024 /1024/ 1024"
    }
   ]
  },
  {
   "title": "Current pods",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod!=\"\"}[24h])) by (pod)"
    },
    {
     "expr": "sum(label_replace(\nsum(avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", container!=\"\",container!=\"POD\"}[24h])) by (pod), \n\"pod_name\",\"$1\",\"pod\",\"(.+)\")\nor up * 0\n) by (pod_name)"
    },
    {
     "expr": "sum(avg_over_time(container_memory_usage_bytes{pod!=\"\"}[24h])) by (pod)\n"
    },
    {
     "expr": "sum(label_replace(label_replace(\nsum(avg_over_time(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", container!=\"\",container!=\"POD\"}[24h])) by (pod),\n\"container_name\",\"$1\",\"container\",\"(.+)\"), \"pod_name\",\"$1\",\"pod\",\"(.+)\")\nor up * 0\n) by (pod_name)\n"
    }
   ]
  },
  {
   "title": "Pods Running (Total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n count(avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", container!=\"\",container!=\"POD\",service=\"opencost\"}[24h])) by (pod)\n * on (pod) group_right()\n sum(kube_pod_container_status_running{service=\"opencost\"}) by (pod)\n)"
    }
   ]
  },
  {
   "title": "Storage Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_node_status_capacity{\n    job=~\"opencost\",\n    resource=\"cpu\",\n    unit=\"core\"\n  }\n) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\", unit=\"byte\",job=\"opencost\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "This panel shows historical utilization for the node.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "timeseries",
   "description": "This panel shows historical utilization for the node.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "description": "Traffic in and out of this namespace, as a sum of the pods within it",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total[10m]))",
     "legendFormat": "<- in"
    },
    {
     "expr": " sum (rate (container_network_transmit_bytes_total[10m]))",
     "legendFormat": "-> out"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "description": "Disk reads and writes for the namespace, as a sum of the pods within it",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_fs_writes_bytes_total[10m]))",
     "legendFormat": "<- write"
    },
    {
     "expr": "sum (rate (container_fs_reads_bytes_total[10m]))",
     "legendFormat": "-> read"
    }
   ]
  }
 ]
}