{
 "title": "OpenCost / Namespace Copy",
 "description": "A dashboard that monitors OpenCost and focuses on namespace costs. It is created using the [opencost-mixin](https://github.com/adinhodovic/opencost-mixin).",
 "tags": [
  "opencost",
  "opencost-mixin"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(opencost_build_info, job)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Finops Middleware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cost Efficiency Score",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(finops_efficiency_score{exported_namespace=\"$namespace\", job=\"finops-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost Anomaly Score",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "finops_anomaly_score{exported_namespace=\"$namespace\", job=~\"finops-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Waste",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}) - \n  sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m]))\n) / sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}) * 100",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg(finops_resource_waste{exported_namespace=\"$namespace\", resource_type=\"memory\", job=\"finops-api\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Monthly LB Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  (\n    sum(kubecost_load_balancer_cost{job=\"$job\", namespace=\"$namespace\"}) by (namespace) * 240.167\n  )\n  or\n  (\n    (1 - scalar(count(kubecost_load_balancer_cost{job=\"$job\", namespace=\"$namespace\"}) or vector(0)))\n    * label_replace(vector(0), \"namespace\", \"$namespace\", \"__name__\", \".*\") \n  ),\n  \"job\", \"\", \"job\", \".*\"\n) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current vs Forecasted Monthly Cost",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  (\n    sum(container_memory_allocation_bytes{namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_ram_hourly_cost) by (instance) / (1024 * 1024 * 1024) * 240.167)\n  )\n  +\n  (\n    sum(container_cpu_allocation{namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_cpu_hourly_cost) by (instance) * 240.167)\n  )\n) by (namespace)",
     "legendFormat": "Current Monthly Cost"
    },
    {
     "expr": "finops_cost_forecast{exported_namespace=\"$namespace\", job=~\"finops-api\"}",
     "legendFormat": " Forecasted Monthly Cost"
    }
   ]
  },
  {
   "title": "Memory Usage vs Requests vs Limits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\"}) / (1024 * 1024 * 1024)",
     "legendFormat": "Mem Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}) / (1024 * 1024 * 1024)",
     "legendFormat": "Mem Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"}) / (1024 * 1024 * 1024)",
     "legendFormat": "Mem Limits"
    }
   ]
  },
  {
   "title": "CPU Usage vs Requests vs Limits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "CPU Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m])) / \nsum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}) * 100",
     "legendFormat": "CPU Efficiency"
    }
   ]
  },
  {
   "title": "Potential Monthly Savings",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "finops_optimization_savings{exported_namespace=\"$namespace\", job=~\"finops-api\"}",
     "legendFormat": "{{recommendation_type}}"
    }
   ]
  },
  { "title": " Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Hourly Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  (\n    sum(container_memory_allocation_bytes{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 1)\n  )\n  +\n  (\n    sum(container_cpu_allocation{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 1)\n  )\n) by (namespace)\n+\n(\n  (\n    sum(\n      label_replace(\n        (\n          kube_persistentvolume_capacity_bytes{job=\"opencost\"} / 1024 / 1024 / 1024\n          * on(persistentvolume)\n            group_left()\n            pv_hourly_cost{job=\"opencost\"}\n        )\n        * on(persistentvolume)\n          group_left(claim_namespace)\n          kube_persistentvolume_claim_ref{claim_namespace=\"$namespace\"}\n        ,\n        \"namespace\", \"$1\", \"claim_namespace\", \"(.*)\"\n      )\n    ) by (namespace)\n  )\n  or\n  (\n    0 * label_replace(vector(1), \"namespace\", \"$namespace\", \"__name__\", \".*\")\n  )\n)\n+\nlabel_replace(\n  (\n    sum(kubecost_load_balancer_cost{job=\"$job\", namespace=\"$namespace\"}) by (namespace)\n  )\n  or\n  (\n    (1 - scalar(count(kubecost_load_balancer_cost{job=\"$job\", namespace=\"$namespace\"}) or vector(0)))\n    * label_replace(vector(0), \"namespace\", \"$namespace\", \"__name__\", \".*\") \n  ),\n  \"job\", \"\", \"job\", \".*\"\n)\n"
    }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  (\n    sum(container_memory_allocation_bytes{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 11)\n  )\n  +\n  (\n    sum(container_cpu_allocation{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 11)\n  )\n) by (namespace)\n+\n(\n  (\n    sum(\n      label_replace(\n        (\n          kube_persistentvolume_capacity_bytes{job=\"opencost\"} / 1024 / 1024 / 1024\n          * on(persistentvolume)\n            group_left()\n            pv_hourly_cost{job=\"opencost\"}\n        )\n        * on(persistentvolume)\n          group_left(claim_namespace)\n          kube_persistentvolume_claim_ref{claim_namespace=\"$namespace\"}\n        ,\n        \"namespace\", \"$1\", \"claim_namespace\", \"(.*)\"\n      )\n    ) by (namespace)\n  )\n  or\n  (\n    0 * label_replace(vector(1), \"namespace\", \"$namespace\", \"__name__\", \".*\")\n  )\n) * 11\n+\nlabel_replace(\n  (\n    sum(kubecost_load_balancer_cost{job=\"$job\", namespace=\"$namespace\"}) by (namespace) * 11\n  )\n  or\n  (\n    (1 - scalar(count(kubecost_load_balancer_cost{job=\"$job\", namespace=\"$namespace\"}) or vector(0)))\n    * label_replace(vector(0), \"namespace\", \"$namespace\", \"__name__\", \".*\") \n  ),\n  \"job\", \"\", \"job\", \".*\"\n)"
    }
   ]
  },
  {
   "title": "Monthly Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  (\n    sum(container_memory_allocation_bytes{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 240.167)\n  )\n  +\n  (\n    sum(container_cpu_allocation{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 240.167)\n  )\n) by (namespace)\n+\n(\n  (\n    sum(\n      label_replace(\n        (\n          kube_persistentvolume_capacity_bytes{job=\"opencost\"} / 1024 / 1024 / 1024\n          * on(persistentvolume)\n            group_left()\n            pv_hourly_cost{job=\"opencost\"}\n        )\n        * on(persistentvolume)\n          group_left(claim_namespace)\n          kube_persistentvolume_claim_ref{claim_namespace=\"$namespace\"}\n        ,\n        \"namespace\", \"$1\", \"claim_namespace\", \"(.*)\"\n      )\n    ) by (namespace)\n  )\n  or\n  (\n    0 * label_replace(vector(1), \"namespace\", \"$namespace\", \"__name__\", \".*\")\n  )\n) * 240.167\n+\n(\nlabel_replace(\n  (\n    sum(kubecost_load_balancer_cost{job=\"$job\", namespace=\"$namespace\"}) by (namespace) * 240.167\n  )\n  or\n  (\n    (1 - scalar(count(kubecost_load_balancer_cost{job=\"$job\", namespace=\"$namespace\"}) or vector(0)))\n    * label_replace(vector(0), \"namespace\", \"$namespace\", \"__name__\", \".*\") \n  ),\n  \"job\", \"\", \"job\", \".*\"\n) or vector(0)\n)"
    }
   ]
  },
  {
   "title": "Monthly CPU Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum(container_cpu_allocation{job=~\"$job\", namespace=~\"$namespace\"})\n  by (namespace, instance)\n  * on(instance) group_left()\n  (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 240.167)\n)\n"
    }
   ]
  },
  {
   "title": "Monthly Ram Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum(container_memory_allocation_bytes{job=~\"$job\", namespace=~\"$namespace\"})\n  by (namespace, instance)\n  * on(instance) group_left()\n  (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 240.167)\n)\n"
    }
   ]
  },
  {
   "title": "Monthly PV Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\nclamp_min(\n  sum(\n    sum(\n      kube_persistentvolume_capacity_bytes{job=~\"$job\"}\n      / (1024 * 1024 * 1024)\n    ) by (persistentvolume)\n    *\n    sum(pv_hourly_cost{job=~\"$job\"}) by (persistentvolume)\n    * on(persistentvolume) group_left(namespace) (\n      label_replace(\n        kube_persistentvolumeclaim_info{job=~\"$job\", namespace=~\"$namespace\"},\n        \"persistentvolume\", \"$1\",\n        \"volumename\", \"(.*)\"\n      )\n    ) \n  ) * 240.167,\n  0\n)\nor vector(0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  (\n    sum(container_memory_allocation_bytes{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 11)\n  )\n  +\n  (\n    sum(container_cpu_allocation{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 11)\n  )\n) by (namespace)\n",
     "legendFormat": "Daily Cost"
    }
   ]
  },
  {
   "title": "Monthly Cost",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  (\n    sum(container_memory_allocation_bytes{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 240.167)\n  )\n  +\n  (\n    sum(container_cpu_allocation{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 240.167)\n  )\n) by (namespace)\n",
     "legendFormat": "Monthly Cost"
    }
   ]
  },
  {
   "title": "Cost by Resource",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum(container_cpu_allocation{job=~\"$job\", namespace=~\"$namespace\"})\n  by (namespace, instance)\n  * on(instance) group_left()\n  (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 240.167)\n)\n",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(\n  sum(container_memory_allocation_bytes{job=~\"$job\", namespace=~\"$namespace\"})\n  by (namespace, instance)\n  * on(instance) group_left()\n  (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 240.167)\n)\n",
     "legendFormat": "RAM"
    },
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{job=~\"$job\"}\n    / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  *\n  sum(pv_hourly_cost{job=~\"$job\"}) by (persistentvolume)\n  * on(persistentvolume) group_left(namespace) (\n    label_replace(\n      kube_persistentvolumeclaim_info{job=~\"$job\", namespace=~\"$namespace\"},\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  )\n) * 240.167\n",
     "legendFormat": "PV"
    },
    {
     "expr": "label_replace(\n  (\n    sum(kubecost_load_balancer_cost{job=\"$job\", namespace=\"$namespace\"}) by (namespace) * 240.167\n  )\n  or\n  (\n    (1 - scalar(count(kubecost_load_balancer_cost{job=\"$job\", namespace=\"$namespace\"}) or vector(0)))\n    * label_replace(vector(0), \"namespace\", \"$namespace\", \"__name__\", \".*\") \n  ),\n  \"job\", \"\", \"job\", \".*\"\n)",
     "legendFormat": "LB"
    }
   ]
  },
  { "title": "Pod Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Pod Monthly Cost",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 240.167)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 240.167)\n    )\n  ) by (pod)\n)\n"
    },
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 240.167)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 240.167)\n    )\n  ) by (pod)\n)\n\n/\ntopk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"} offset 7d)\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"} offset 7d) by (instance) / (1024 * 1024 * 1024) * 240.167)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"} offset 7d)\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"} offset 7d) by (instance) * 240.167)\n    )\n  ) by (pod)\n)\n\n* 100\n- 100\n"
    },
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 240.167)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 240.167)\n    )\n  ) by (pod)\n)\n\n/\ntopk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"} offset 30d)\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"} offset 30d) by (instance) / (1024 * 1024 * 1024) * 240.167)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"} offset 30d)\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"} offset 30d) by (instance) * 240.167)\n    )\n  ) by (pod)\n)\n\n* 100\n- 100\n"
    }
   ]
  },
  {
   "title": "Cost by Pod",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 240.167)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 240.167)\n    )\n  ) by (pod)\n)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Container Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Container Monthly Cost",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 240.167)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 240.167)\n    )\n  ) by (container)\n)\n"
    },
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 240.167)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 240.167)\n    )\n  ) by (container)\n)\n\n/\ntopk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"} offset 7d)\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"} offset 7d) by (instance) / (1024 * 1024 * 1024) * 240.167)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"} offset 7d)\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"} offset 7d) by (instance) * 240.167)\n    )\n  ) by (container)\n)\n\n* 100\n- 100\n"
    },
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 240.167)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 240.167)\n    )\n  ) by (container)\n)\n\n/\ntopk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"} offset 30d)\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"} offset 30d) by (instance) / (1024 * 1024 * 1024) * 240.167)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"} offset 30d)\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"} offset 30d) by (instance) * 240.167)\n    )\n  ) by (container)\n)\n\n* 100\n- 100\n"
    }
   ]
  },
  {
   "title": "Cost by Container",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 240.167)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 240.167)\n    )\n  ) by (container)\n)\n",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "PV Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Persistent Volumes Monthly Cost",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(\n  sum(kube_persistentvolume_capacity_bytes{job=~\"$job\"} / (1024 * 1024 * 1024))\n  by (persistentvolume)\n  * on(persistentvolume) group_left(namespace)\n    label_replace(\n      kube_persistentvolumeclaim_info{job=~\"$job\", namespace=~\"$namespace\"},\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  * sum(pv_hourly_cost{job=~\"$job\"}) by (persistentvolume)\n) by (persistentvolume) * 240.167\n"
    },
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{job=~\"$job\"}\n    / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  *\n  sum(pv_hourly_cost{job=~\"$job\"}) by (persistentvolume)\n  * on(persistentvolume) group_left(namespace) (\n    label_replace(\n      kube_persistentvolumeclaim_info{job=~\"$job\", namespace=~\"$namespace\"},\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  )\n) by (persistentvolume) * 240.167\n"
    }
   ]
  },
  {
   "title": "Cost by PV",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{job=~\"$job\"}\n    / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  *\n  sum(pv_hourly_cost{job=~\"$job\"}) by (persistentvolume)\n  * on(persistentvolume) group_left(namespace) (\n    label_replace(\n      kube_persistentvolumeclaim_info{job=~\"$job\", namespace=~\"$namespace\"},\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  )\n) by (persistentvolume) * 240.167\n",
     "legendFormat": "{{ persistentvolume }}"
    }
   ]
  }
 ]
}