{
 "title": "OpenCost / Overview",
 "description": "A dashboard that monitors OpenCost and focuses on giving a overview for OpenCost. It is created using the [opencost-mixin](https://github.com/adinhodovic/opencost-mixin).",
 "tags": [
  "opencost",
  "opencost-mixin"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(opencost_build_info, job)"
   }
  ]
 },
 "panels": [
  { "title": "Finops Middleware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Potential Savings",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(finops_optimization_savings)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potential Savings by Recommendation Type",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(finops_optimization_savings{recommendation_type!=\"add_cpu_limits\",recommendation_type!=\"add_cpu_limits_and_requests\",recommendation_type!=\"add_memory_limits\",recommendation_type!=\"add_memory_limits_and_requests\"}) by (recommendation_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost Efficiency by Namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "finops_efficiency_score{job=~\"finops-api\"}",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Cost Anomalies by Namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "finops_anomaly_score{job=~\"finops-api\"}",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  { "title": "Cluster Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Monthly Cost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    job=~\"$job\"\n  }\n) * 240.167\n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (persistentvolume)\n) * 240.167\n+\nsum(kubecost_load_balancer_cost) * 240.167"
    }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    job=~\"$job\"\n  }\n) * 11  \n+\nsum(\nsum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (persistentvolume)\n) * 11\n+\nsum(kubecost_load_balancer_cost) * 11\n"
    }
   ]
  },
  {
   "title": "Monthly CPU Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_node_status_capacity{\n      job=~\"$job\",\n      resource=\"cpu\",\n      unit=\"core\"\n    }\n  ) by (node)\n  * on(node) group_left()\n    sum(\n      node_cpu_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (node)\n  * 240.167\n)\n"
    }
   ]
  },
  {
   "title": "Monthly PV Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n    sum(\n      pv_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (persistentvolume)\n) * 240.167\n"
    }
   ]
  },
  {
   "title": "Hourly Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    job=~\"$job\"\n  }\n) \n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (persistentvolume)\n) \n+\nsum(kubecost_load_balancer_cost)\n"
    }
   ]
  },
  {
   "title": "Monthly Ram Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_node_status_capacity{\n      job=~\"$job\",\n      resource=\"memory\",\n      unit=\"byte\"\n    }\n  ) by (node)\n  / (1024 * 1024 * 1024)\n  * on(node) group_left()\n    sum(\n      node_ram_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (node)\n  * 240.167\n)\n"
    }
   ]
  },
  {
   "title": "LoadBalacer Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubecost_load_balancer_cost) * 240.167",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hourly Cost",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    job=~\"$job\"\n  }\n) \n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (persistentvolume)\n) \n+\nsum(kubecost_load_balancer_cost)",
     "legendFormat": "Hourly Cost"
    }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    job=~\"$job\"\n  }\n) * 11\n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (persistentvolume)\n) * 11\n+\nsum(kubecost_load_balancer_cost) * 11",
     "legendFormat": "Daily Cost"
    }
   ]
  },
  {
   "title": "Monthly Cost",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    job=~\"$job\"\n  }\n) * 240.167\n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (persistentvolume)\n) * 240.167\n+\nsum(kubecost_load_balancer_cost) * 240.167",
     "legendFormat": "Monthly Cost"
    }
   ]
  },
  {
   "title": "Cost by Resource",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_node_status_capacity{\n      job=~\"$job\",\n      resource=\"cpu\",\n      unit=\"core\"\n    }\n  ) by (node)\n  * on(node) group_left()\n    sum(\n      node_cpu_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (node)\n  * 240.167\n)\n",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(\n  sum(\n    kube_node_status_capacity{\n      job=~\"$job\",\n      resource=\"memory\",\n      unit=\"byte\"\n    }\n  ) by (node)\n  / (1024 * 1024 * 1024)\n  * on(node) group_left()\n    sum(\n      node_ram_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (node)\n  * 240.167\n)\n",
     "legendFormat": "RAM"
    },
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n    sum(\n      pv_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (persistentvolume)\n) * 240.167\n",
     "legendFormat": "PV"
    },
    {
     "expr": "sum(kubecost_load_balancer_cost)*240.167",
     "legendFormat": "Load Balancer"
    }
   ]
  },
  {
   "title": "Cost by Namespace",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    sum(\n      container_memory_allocation_bytes{job=~\"$job\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (node_ram_hourly_cost{job=~\"$job\"} / (1024 * 1024 * 1024) * 240.167)\n    +\n    sum(\n      container_cpu_allocation{job=~\"$job\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (node_cpu_hourly_cost{job=~\"$job\"} * 240.167)\n  ) by (namespace)\n)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Cost by Instance Type",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    node_total_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (instance_type) * 240.167\n)\n",
     "legendFormat": "{{ instance_type }}"
    }
   ]
  },
  {
   "title": "Total Cost Variance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 -\n(\n  avg_over_time(\n    sum(node_total_hourly_cost{job=~\"$job\"}) [7d:1h]\n  )\n  /\n  avg_over_time(\n    sum(node_total_hourly_cost{job=~\"$job\"}) [1d:1h]\n  )\n)\n",
     "legendFormat": "Current hourly cost vs. 7-day average"
    },
    {
     "expr": "1 -\n(\n  avg_over_time(\n    sum(node_total_hourly_cost{job=~\"$job\"}) [30d:1h]\n  )\n  /\n  avg_over_time(\n    sum(node_total_hourly_cost{job=~\"$job\"}) [1d:1h]\n  )\n)\n",
     "legendFormat": "Current hourly cost vs. 30-day average"
    }
   ]
  },
  {
   "title": "Resource Cost Variance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 -\n(\n  avg_over_time(\n    sum(\n  sum(\n    kube_node_status_capacity{\n      job=~\"$job\",\n      resource=\"cpu\",\n      unit=\"core\"\n    }\n  ) by (node)\n  * on(node) group_left()\n    sum(\n      node_cpu_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (node)\n  * 240.167\n)\n [30d:1h]\n  )\n  /\n  avg_over_time(\n    sum(\n  sum(\n    kube_node_status_capacity{\n      job=~\"$job\",\n      resource=\"cpu\",\n      unit=\"core\"\n    }\n  ) by (node)\n  * on(node) group_left()\n    sum(\n      node_cpu_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (node)\n  * 240.167\n)\n [1d:1h]\n  )\n)\n",
     "legendFormat": "Current CPU hourly cost vs. 30-day average"
    },
    {
     "expr": "1 -\n(\n  avg_over_time(\n    sum(\n  sum(\n    kube_node_status_capacity{\n      job=~\"$job\",\n      resource=\"memory\",\n      unit=\"byte\"\n    }\n  ) by (node)\n  / (1024 * 1024 * 1024)\n  * on(node) group_left()\n    sum(\n      node_ram_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (node)\n  * 240.167\n)\n [30d:1h]\n  )\n  /\n  avg_over_time(\n    sum(\n  sum(\n    kube_node_status_capacity{\n      job=~\"$job\",\n      resource=\"memory\",\n      unit=\"byte\"\n    }\n  ) by (node)\n  / (1024 * 1024 * 1024)\n  * on(node) group_left()\n    sum(\n      node_ram_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (node)\n  * 240.167\n)\n [1d:1h]\n  )\n)\n",
     "legendFormat": "Current RAM hourly cost vs. 30-day average"
    },
    {
     "expr": "1 -\n(\n  avg_over_time(\n    (sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n    sum(\n      pv_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (persistentvolume)\n) * 240.167\n) [30d:1h]\n  )\n  /\n  avg_over_time(\n    (sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n    sum(\n      pv_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (persistentvolume)\n) * 240.167\n) [1d:1h]\n  )\n)\n",
     "legendFormat": "Current PV hourly cost vs. 30-day average"
    }
   ]
  },
  { "title": "Cloud Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Nodes Monthly Cost",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  kube_node_status_capacity{\n    job=~\"$job\",\n    resource=\"cpu\",\n    unit=\"core\"\n  }\n) by (node)\n* on(node) group_left(instance_type, arch)\n  sum(\n    node_cpu_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (node, instance_type, arch)\n* 240.167\n"
    },
    {
     "expr": "sum(\n  kube_node_status_capacity{\n    job=~\"$job\",\n    resource=\"memory\",\n    unit=\"byte\"\n  }\n) by (node)\n/ (1024 * 1024 * 1024)\n* on(node) group_left(instance_type, arch)\n  sum(\n    node_ram_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (node, instance_type, arch)\n* 240.167\n"
    },
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    job=~\"$job\"\n  }\n) by (node, instance_type, arch)\n* 240.167\n"
    }
   ]
  },
  {
   "title": "Persistent Volumes Monthly Cost",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(\n  kube_persistentvolume_capacity_bytes{\n    job=~\"$job\"\n  }\n  / 1024 / 1024 / 1024\n) by (persistentvolume)\n"
    },
    {
     "expr": "sum(\n  kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    }\n  / 1024 / 1024 / 1024\n) by (persistentvolume)\n*\nsum(\n  pv_hourly_cost{\n    job=~\"$job\"\n  }\n  * 240.167\n) by (persistentvolume)\n"
    }
   ]
  },
  { "title": "Namespace Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Namespace Monthly Cost",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\n  (\n    ## CPU + Memória\n    sum(\n      sum(container_memory_allocation_bytes{job=\"opencost\"}) by (namespace, instance)\n      * on(instance) group_left()\n        (node_ram_hourly_cost{job=\"opencost\"} / (1024 * 1024 * 1024) * 240.167)\n    ) by (namespace)\n    +\n    sum(\n      sum(container_cpu_allocation{job=\"opencost\"}) by (namespace, instance)\n      * on(instance) group_left()\n        (node_cpu_hourly_cost{job=\"opencost\"} * 240.167)\n    ) by (namespace)\n\n    ## Load Balancer\n    +\n    (\n      sum(kubecost_load_balancer_cost{job=\"opencost\"} * 240.167) by (namespace)\n      or\n      (\n        0 * label_replace(\n          sum(container_cpu_allocation{job=\"opencost\"}) by (namespace),\n          \"namespace\", \"$1\", \"namespace\", \"(.*)\"\n        )\n      )\n    )\n\n    ## Persistent Volumes\n    +\n    (\n      sum(\n        label_replace(\n          (\n            kube_persistentvolume_capacity_bytes{job=\"opencost\"} / 1024 / 1024 / 1024\n            * on(persistentvolume)\n              group_left()\n              (pv_hourly_cost{job=\"opencost\"} * 240.167)\n          )\n          * on(persistentvolume)\n            group_left(claim_namespace)\n            kube_persistentvolume_claim_ref\n          ,\n          \"namespace\", \"$1\", \"claim_namespace\", \"(.*)\"\n        )\n      ) by (namespace)\n      or\n      (\n        0 * label_replace(\n          sum(container_cpu_allocation{job=\"opencost\"}) by (namespace),\n          \"namespace\", \"$1\", \"namespace\", \"(.*)\"\n        )\n      )\n    )\n  )\n)\n\n"
    },
    {
     "expr": "topk(10,\n  (\n    ## CPU + Memória\n    sum(\n      sum(container_memory_allocation_bytes{job=\"opencost\"}) by (namespace, instance)\n      * on(instance) group_left()\n        (node_ram_hourly_cost{job=\"opencost\"} / (1024 * 1024 * 1024) * 240.167)\n    ) by (namespace)\n    +\n    sum(\n      sum(container_cpu_allocation{job=\"opencost\"}) by (namespace, instance)\n      * on(instance) group_left()\n        (node_cpu_hourly_cost{job=\"opencost\"} * 240.167)\n    ) by (namespace)\n\n    ## Load Balancer\n    +\n    (\n      sum(kubecost_load_balancer_cost{job=\"opencost\"} * 240.167) by (namespace)\n      or\n      (\n        0 * label_replace(\n          sum(container_cpu_allocation{job=\"opencost\"}) by (namespace),\n          \"namespace\", \"$1\", \"namespace\", \"(.*)\"\n        )\n      )\n    )\n\n    ## Persistent Volumes\n    +\n    (\n      sum(\n        label_replace(\n          (\n            kube_persistentvolume_capacity_bytes{job=\"opencost\"} / 1024 / 1024 / 1024\n            * on(persistentvolume)\n              group_left()\n              (pv_hourly_cost{job=\"opencost\"} * 240.167)\n          )\n          * on(persistentvolume)\n            group_left(claim_namespace)\n            kube_persistentvolume_claim_ref\n          ,\n          \"namespace\", \"$1\", \"claim_namespace\", \"(.*)\"\n        )\n      ) by (namespace)\n      or\n      (\n        0 * label_replace(\n          sum(container_cpu_allocation{job=\"opencost\"}) by (namespace),\n          \"namespace\", \"$1\", \"namespace\", \"(.*)\"\n        )\n      )\n    )\n  )\n)\n\n/\n  topk(10,\n    (\n      ## CPU + Memória (7 dias atrás)\n      sum(\n        sum(container_memory_allocation_bytes{job=\"opencost\"} offset 7d) by (namespace, instance)\n        * on(instance) group_left()\n          (node_ram_hourly_cost{job=\"opencost\"} offset 7d / (1024 * 1024 * 1024) * 240.167)\n      ) by (namespace)\n      +\n      sum(\n        sum(container_cpu_allocation{job=\"opencost\"} offset 7d) by (namespace, instance)\n        * on(instance) group_left()\n          (node_cpu_hourly_cost{job=\"opencost\"} offset 7d * 240.167)\n      ) by (namespace)\n\n      ## Load Balancer\n      +\n      (\n        sum(kubecost_load_balancer_cost{job=\"opencost\"} offset 7d * 240.167) by (namespace)\n        or\n        (\n          0 * label_replace(\n            sum(container_cpu_allocation{job=\"opencost\"} offset 7d) by (namespace),\n            \"namespace\", \"$1\", \"namespace\", \"(.*)\"\n          )\n        )\n      )\n\n      ## Persistent Volumes\n      +\n      (\n        sum(\n          label_replace(\n            (\n              kube_persistentvolume_capacity_bytes{job=\"opencost\"} offset 7d / 1024 / 1024 / 1024\n              * on(persistentvolume)\n                group_left()\n                (pv_hourly_cost{job=\"opencost\"} offset 7d * 240.167)\n            )\n            * on(persistentvolume)\n              group_left(claim_namespace)\n              kube_persistentvolume_claim_ref offset 7d\n            ,\n            \"namespace\", \"$1\", \"claim_namespace\", \"(.*)\"\n          )\n        ) by (namespace)\n        or\n        (\n          0 * label_replace(\n            sum(container_cpu_allocation{job=\"opencost\"} offset 7d) by (namespace),\n            \"namespace\", \"$1\", \"namespace\", \"(.*)\"\n          )\n        )\n      )\n    )\n  )\n* 100 - 100"
    },
    {
     "expr": "topk(10,\n  (\n    ## CPU + Memória\n    sum(\n      sum(container_memory_allocation_bytes{job=\"opencost\"}) by (namespace, instance)\n      * on(instance) group_left()\n        (node_ram_hourly_cost{job=\"opencost\"} / (1024 * 1024 * 1024) * 240.167)\n    ) by (namespace)\n    +\n    sum(\n      sum(container_cpu_allocation{job=\"opencost\"}) by (namespace, instance)\n      * on(instance) group_left()\n        (node_cpu_hourly_cost{job=\"opencost\"} * 240.167)\n    ) by (namespace)\n\n    ## Load Balancer\n    +\n    (\n      sum(kubecost_load_balancer_cost{job=\"opencost\"} * 240.167) by (namespace)\n      or\n      (\n        0 * label_replace(\n          sum(container_cpu_allocation{job=\"opencost\"}) by (namespace),\n          \"namespace\", \"$1\", \"namespace\", \"(.*)\"\n        )\n      )\n    )\n\n    ## Persistent Volumes\n    +\n    (\n      sum(\n        label_replace(\n          (\n            kube_persistentvolume_capacity_bytes{job=\"opencost\"} / 1024 / 1024 / 1024\n            * on(persistentvolume)\n              group_left()\n              (pv_hourly_cost{job=\"opencost\"} * 240.167)\n          )\n          * on(persistentvolume)\n            group_left(claim_namespace)\n            kube_persistentvolume_claim_ref\n          ,\n          \"namespace\", \"$1\", \"claim_namespace\", \"(.*)\"\n        )\n      ) by (namespace)\n      or\n      (\n        0 * label_replace(\n          sum(container_cpu_allocation{job=\"opencost\"}) by (namespace),\n          \"namespace\", \"$1\", \"namespace\", \"(.*)\"\n        )\n      )\n    )\n  )\n)\n\n/\n  topk(10,\n    (\n      ## CPU + Memória (7 dias atrás)\n      sum(\n        sum(container_memory_allocation_bytes{job=\"opencost\"} offset 30d) by (namespace, instance)\n        * on(instance) group_left()\n          (node_ram_hourly_cost{job=\"opencost\"} offset 30d / (1024 * 1024 * 1024) * 240.167)\n      ) by (namespace)\n      +\n      sum(\n        sum(container_cpu_allocation{job=\"opencost\"} offset 30d) by (namespace, instance)\n        * on(instance) group_left()\n          (node_cpu_hourly_cost{job=\"opencost\"} offset 30d * 240.167)\n      ) by (namespace)\n\n      ## Load Balancer\n      +\n      (\n        sum(kubecost_load_balancer_cost{job=\"opencost\"} offset 30d * 240.167) by (namespace)\n        or\n        (\n          0 * label_replace(\n            sum(container_cpu_allocation{job=\"opencost\"} offset 30d) by (namespace),\n            \"namespace\", \"$1\", \"namespace\", \"(.*)\"\n          )\n        )\n      )\n\n      ## Persistent Volumes\n      +\n      (\n        sum(\n          label_replace(\n            (\n              kube_persistentvolume_capacity_bytes{job=\"opencost\"} offset 30d / 1024 / 1024 / 1024\n              * on(persistentvolume)\n                group_left()\n                (pv_hourly_cost{job=\"opencost\"} offset 30d * 240.167)\n            )\n            * on(persistentvolume)\n              group_left(claim_namespace)\n              kube_persistentvolume_claim_ref offset 30d\n            ,\n            \"namespace\", \"$1\", \"claim_namespace\", \"(.*)\"\n          )\n        ) by (namespace)\n        or\n        (\n          0 * label_replace(\n            sum(container_cpu_allocation{job=\"opencost\"} offset 30d) by (namespace),\n            \"namespace\", \"$1\", \"namespace\", \"(.*)\"\n          )\n        )\n      )\n    )\n  )\n* 100 - 100"
    }
   ]
  }
 ]
}