apiVersion: v1
kind: Namespace
metadata:
  name: finops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finops-api
  namespace: finops
  labels:
    app: finops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finops-api
  template:
    metadata:
      labels:
        app: finops-api
    spec:
      containers:
      - name: finops-api
        image: finops-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: PROMETHEUS_URL
          value: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"
        - name: OPENCOST_URL
          value: "http://opencost.opencost.svc.cluster.local:9003"
        - name: GRAFANA_URL
          value: "http://prometheus-grafana.monitoring.svc.cluster.local:3000"
        - name: CPU_HOURLY_COST
          value: "0.04"
        - name: MEMORY_GB_HOURLY_COST
          value: "0.01"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: finops-api
  namespace: finops
spec:
  selector:
    app: finops-api
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finops-api
  namespace: finops
spec:
  ingressClassName: nginx
  rules:
    - host: finops-api
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: finops-api
                port:
                  number: 8000